### ISSUE TITLE
when loading custom ply using the steps from tanks it doesn't get color

### ISSUE THREAD

**Issue by AndreV84** [heremaps/pptk#48]
`python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import pptk
>>> import plyfile
>>> data = plyfile.PlyData.read('cloud.ply')['vertex']
>>> xyz = np.c_[data['x'], data['y'], data['z']]
>>> rgb = np.c_[data['red'], data['green'], data['blue']]
>>> n = np.c_[data['nx'], data['ny'], data['nz']]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nvidia/.local/lib/python3.6/site-packages/plyfile.py", line 770, in __getitem__
    return self.data[key]
  File "/home/nvidia/.local/lib/python3.6/site-packages/numpy/core/memmap.py", line 331, in __getitem__
    res = super(memmap, self).__getitem__(index)
ValueError: no field of name nx`

**Comment by AndreV84** [comment]
could you also extend on the installation issuees, please?
https://forums.developer.nvidia.com/t/building-pptk-on-xavier-how-to-get-through/160079

**Comment by nikste** [comment]
Hi, this issue has been fixed in [pptk-revived](https://github.com/nikste/pptk-revived), a fork that I'm actively maintaining since development on this repository appears to have stalled.                                                                                                                          

You can install it with:
`pip install pptk-revived` 

It's a drop-in replacement — just import pptk works as before. I'm working through the open issues here one by one. Contributions and feedback are welcome!

**Comment by AndreV84** [comment]
it returns 
`ImportError: cannot import name 'kdtree' from 'pptk.kdtree' (/home/user/pptk-revived/pptk/kdtree/__init__.py)`

**Comment by nikste** [comment]
can you tell me more about how you installed it ? 
Python version?
did you build from source or installed it with pip ?
Did you run it from within the pptk source folder?

I tried it locally and all of those cases seem to work for me.
